swagger: "3.0"
info:
  description: "This API handles hashing a password supplied in a form request and providing statistics."
  version: "0.0.1"
  title: "JumpCloud Hashing API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "wilson.travis.t@gmail.com"
  license:
    name: "MIT"
basePath: "/"
schemes:
  - "http"
paths:
  /healthcheck:
    get:
      summary: "Simple healthcheck that returns the version of the API, current time."
      produces:
        - "application/json"
  /hash:
    post:
      summary: "Handles hashing and encoding of the supplied password in the form data."
      consumes:
        - "application/x-www-form-urlencoded"
      produces:
        - "application/json"
      parameters:
        - name: "password"
          in: "formData"
          description: "Password to be hashed and encoded"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hash"
        "400":
          description: "Request body missing required fields"
definitions:
  Hash:
    type: "object"
    properties:
      id:
        type: "integer"
        description: ""
        format: "int64"