openapi: 3.0.0
info:
  description: "This API handles hashing a password supplied in a form request and providing statistics."
  version: "0.0.1"
  title: "JumpCloud Hashing API"
  contact:
    email: "wilson.travis.t@gmail.com"
  license:
    name: "MIT"
paths:
  /hash:
    post:
      summary: "Handles hashing and encoding of the supplied password in the form data."
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                password:
                  description: Password value to be hashed.
                  type: string
                  required: true
      responses:
        "200":
          description: "Returns the identifier for the submited hash."
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: "Request body missing required fields"
  /hash/{id}:
    get:
      summary: "Returns the hashed password for the given id"
      parameters:
        - name: id
          in: path
          required: true
          description: Identifier for the hashed value returned in `/hash` request.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200":
          description: "Returns the hashed value "
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: "Identifier not saved or is still in process of saving."
        "400":
          description: "Identifier is invalid."
  /stats:
    get:
      summary: "Returns the stats from the system at the current request time."
      responses:
        "200":
          description: "Returns the identifier for the submited hash."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
  /shutdown:
    get:
      summary: "Starts the shutdown process for the server. This will wait till all executing hash jobs finishes."
      responses:
        "200":
          description: "Successfully started shutdown process."
components:
  schemas:
    Stats:
      type: "object"
      properties:
        total:
          type: "integer"
          description: "The total number of identifiers created."
          format: "int64"
        average:
          type: "integer"
          description: "The average request time in microseconds for `/hash`"
          format: "int64"